"""add is_published field

Revision ID: 9d320b92df16
Revises: 0c517b808556
Create Date: 2026-07-19 18:11:32.958473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d320b92df16'
down_revision: Union[str, Sequence[str], None] = '0c517b808556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_post_is_published'), 'post', ['is_published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_is_published'), table_name='post')
    op.drop_column('post', 'is_published')
    # ### end Alembic commands ###
